# fast-scalp-crypto-bot/render.yaml
services:
  - type: worker
    name: fast-scalp-crypto-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MEXC_API_KEY
        sync: false
      - key: MEXC_SECRET_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    plan: free
    numInstances: 1
